fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.19.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "4.5.1"
    yum:
      repo: "puppet/yum"
      ref: "2.2.1"
    zypprepo:
      repo: "puppet/zypprepo"
      ref: "2.2.1"
